### ISSUE TITLE
todo for first-order structure analysis

### ISSUE THREAD

**Issue by dyurovsky** [cbergey/childlanguageinfo#1]
NB: entropy has length/frequency confounds. Simon has an entropy estimator that works ok, the R entropy package has a bunch of estimators

**Entropy**
- [ ] compare entropy over frames between parents, children, and adults in switchboard
- [x] entropy of frames in children and parents over development
- [x] correlation between entropies of between conversational partners vs. random conversational partners at the same age
- [x] are there particular frames the are frequent/infrequent in children/parents/adults?
- [x] try using the NSB estimator for entropy
- [x] entropy of words/POS in children and parents over development
- [x] entropy over actual utts in children and parents over development

**KL**
- [ ] KL divergence versions of these same measures (i.e. do kids and parents look more like each-other over development)

**Other**
- [ ] do frames with words in them differ substantially from the fully parsed frames. Maybe measure as entropy over utterances within parsed frames?
- [ ] manipulate top N to see if measures change
- [ ] look at Zipf's law coefficient or fit (or other language statistics) to see if they change over development etc and depend on N
- [ ] maybe look at particular frames (e.g. those from the frame papers) to see how they behave

**Comment by simon-dedeo** [comment]
Excellent! 

Simon DeDeo
Carnegie Mellon University & the Santa Fe Institute
http://santafe.edu/~simon
